### ISSUE TITLE
AI generated content in markdown is messy

### ISSUE THREAD

**Issue by jt6677** [steven-tey/novel#58] opened 2023-06-28 15:05 UTC
![1](https://github.com/steven-tey/novel/assets/62420169/4443c4cf-6dba-4f4c-bf76-c02dc82b2721)
![2](https://github.com/steven-tey/novel/assets/62420169/cb36ceb9-9b22-488c-8557-faf5deaa892a)
openAI's response does not play nice with new markdown feature. My guess you need to force the response to be plain text.

**Comment by steven-tey** [comment] 2023-06-28 15:07
Yeahhh I [noticed that too](https://github.com/steven-tey/novel/discussions/7#discussioncomment-6299988) – might need to coerce that to plaintext for now <picture data-single-emoji=":meow_disappointed:" title=":meow_disappointed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/meow_disappointed/6aab6bfc3d081320.png" alt=":meow_disappointed:" align="absmiddle"></picture>

**Comment by jt6677** [comment] 2023-06-28 15:10
That would have issue too. Previously, the gtp response would have a nice format but any editing of the response would cause the text to lose all the line break.  I could not find a solution to that problem at the moment.

**Comment by steven-tey** [comment] 2023-06-28 17:05
@jt6677 yeah that's smart! The root of the issue is streaming response doesn't play well with the way they're converted into markdown by `tiptap-markdown` – the maintainer of the lib, @aguingand confirmed that as well!

Setting everything with `setContent` when the response finishes streaming would work, but it becomes a blocking response and defeats the purpose of streaming: https://github.com/steven-tey/novel/discussions/7#discussioncomment-6299988

**Comment by jt6677** [comment] 2023-06-29 09:49
@steven-tey   I came close with a solution. 
```
//temporarily escape markdown syntax as stream coming in  
useEffect(() => {
  const diff = completion.slice(prev.current.length);
  prev.current = completion;

  // Escape markdown syntax
  const escapedDiff = diff.replace(/([#*_{}[\]()`~>#+-.!|])/g, '\\$1');

  // Replace the content in the editor with the escaped markdown
  editor?.commands.setContent(escapedDiff, false);

}, [isLoading, editor, completion]);
```         

```
\\ parse it again onFinish 

onFinish: (_prompt, completion) => {
  if (!editor) return
  console.log('🚀 ~ file: Editor.tsx:116 ~ Editor ~ completion:', completion)
  const from = editor.state.selection.from - completion.length
  const to = editor.state.selection.from

  // Replace the current content in the editor with the completion, parsed as Markdown
  editor.commands.setContent(completion, false);
},
``` 
 The problem is setContent would work but not insertContent. setContent replaces everything.  Maybe someone with better knowledge with tiptap would know what to do here.

**Comment by peterokwara** [comment] 2023-07-07 16:38
@jt6677 ended up doing the same thing.
I stream the content. Then when the streaming finishes, I set it. Will work for now.

**Comment by jt6677** [comment] 2023-07-07 17:09
> 

yeah, tiptap markdown does not play nice with streamed response. You either need to escape all the markdown syntax while streaming then set it again or just no using markdown at all. I delete the markdown plugin because the markdown was just too unpredictable.

**Comment by haydenbleasel** [comment] 2024-03-16 18:52
@andrewdoro This issue is likely resolved by the new AI implementation since it's not streamed into the editor directly.

**Comment by andrewdoro** [comment] 2024-03-17 10:39
@haydenbleasel Yep thanks for the tag here. So the new AI implementation works with Markdown. We no longer have a working example for the old `++` implementation where we stream directly in the editor. (if someone wants to work with that, the current AI code might help).

I also recommend the new approach. This is what Notion also uses.

**Closed by andrewdoro** 2024-03-17 10:39 UTC

**Comment by bakikucukcakiroglu** [comment] 2024-07-30 17:37
@andrewdoro  I need to stream AI content directly into the editor. Isn't there a way of doing this? I almost finished the project and encountered this problem. I should start from scratch using a different editor if I cannot find a solution.
